clinic-info:
  name: 'my clinic'
  working-hours: '8-17'

doctor-config:
    specializations:
      - 'Surgeon'
      - 'Dentist'
      - 'Psychologist'

spring:
    datasource:
        url: jdbc:postgresql:pet_clinic
        username: postgres
        password: root

    jackson.property-naming-strategy: SNAKE_CASE
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: update

logging.level.org.hibernate: DEBUG


