clinic-info:
  name: 'my clinic'
  working-hours: '8-17'

doctor-config:
    specializations:
      - 'Surgeon'
      - 'Dentist'
      - 'Psychologist'

spring:
    datasource:
        url: jdbc:postgresql:pet_clinic
        username: postgres
        password: root

    jackson:
      #property-naming-strategy: SNAKE_CASE
      serialization:
        write_dates_as_timestamps: false
        indent-output: true
    jpa:
        #show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: create
        open-in-view: false

---
spring:
  profiles: prod
  datasource:
          url: jdbc:postgresql:pet_clinic
          username: postgres
          password: root

  jackson.serialization.indent-output: false
  #jpa.hibernate.ddl-auto: validate
#logging.level.org.hibernate: DEBUG


